### ISSUE TITLE
review request

### ISSUE THREAD

**Issue by CC11001100** [golang-infrastructure/go-try-catch#1]
彬爷怎么看？ @songzhibin97

**Comment by songzhibin97** [comment]
感觉不太好用的亚子

**Comment by CC11001100** [comment]
> 感觉不太好用的亚子

有没有具体的改进建议呢

**Comment by songzhibin97** [comment]
局部的如果传入func里面 go func 一些内容, panic依然是无法捕获, 而且这种写法感觉也比较难受

**Comment by CC11001100** [comment]
> 局部的如果传入func里面 go func 一些内容, panic依然是无法捕获, 而且这种写法感觉也比较难受

1. 不能在一个协程中捕获其它协程中抛出的异常，这也不能算是Go的设计缺陷，我之前也骂过感觉智障，但后来查了一下编程语言似乎都是这么干的，协程或线程就不是这么用的，是我的编程习惯有问题。。。
2. 难受的问题确实存在，尤其是对没接触过try-catch这种模式的人来说，我也在想在Go现有的语法之下怎么做能够写得爽又能读得快，有什么具体的建议吗

**Comment by songzhibin97** [comment]
可以使用比较hack的方法， linkname出fatapanic 在patch，但是本质上没法使程序继续运行，感觉意义不大
